### ISSUE TITLE
Undefined property: MongoDB\BSON\UTCDateTime::$sec 

### ISSUE THREAD

**Issue by cherbert** [alcaeus/mongo-php-adapter#105]
A lot of our code uses the sec property on mongo date objects.

e.g

$mydate->sec;

This works fine on the old Mongo PHP driver but using this adapter returns an Undefined property. Is there an alternate solution or fix?

**Comment by alcaeus** [comment]
Since you've closed this yourself, may I assume the issue is fixed? If you look at the code you'll find that the `sec` and `usec` properties in `MongoDate` are public, so you should be able to access them without any problem.
If this is indeed still happening, can you please share the code that produces the error? Normally you shouldn't even have to work with a `UTCDateTime` object since the adapter handles type conversion.

**Comment by cherbert** [comment]
It was my mistake. I was trying to call $mydate->sec on an date object retreived from jenssegers newest version of mongo driver for laravel.
