### ISSUE TITLE
How to use it for application without composer?

### ISSUE THREAD

**Issue by gaoyichuan** [alcaeus/mongo-php-adapter#109]
You did a wonderful job! But I want to use it for RockMongo but it doesn't use composer for package managing, so can this adapter work for it? I would appreciate it a lot if you can help me.

**Comment by alcaeus** [comment]
To be honest, no. You'll have to manually resolve all dependencies this library has (e.g. mongo-php-library and its dependencies) and then load the required classes. Your best bet is probably installing the dependencies using composer and including the composer autoload file somewhere in RockMongo. Since I'm not familiar with the codebase I can't help out much, either.

**Comment by gaoyichuan** [comment]
Oh, thanks anyway

**Comment by gruberro** [comment]
Maybe https://packagist.org/packages/myurasov/rockmongo can help you?
