### ISSUE TITLE
No suitable servers found error after first five minutes.

### ISSUE THREAD

**Issue by nurolopher** [alcaeus/mongo-php-adapter#143]
First of all, let me tell you the technology stack I am using.

- PHP 7.1.0
- Symfony 3.2
- Doctrine MongoDB ODM
- mongo-php-adapter 1.0.7
- mongodb extension 1.2.1
- libmongoc 1.50
- libbson 1.5.0
- mac Os, Linux Debian jessie

**Situation**

When I first launch the server and make requests to the **mongodb server** it works fine. I get the desired results. But it only lasts for a couple of minutes, more than 5 minutes. After 5 minutes I get **No suitable servers found** error. But if I refresh the browser, I get a normal response again. Then after 5 or more minutes I get the same error. Loop, goes on like this.

I have read following from official php.net site.

> All versions of the driver since 1.2.0 persist the » libmongoc client object in the PHP worker process, which allows it to re-use database connections, authentication states, and topology information across multiple requests.
 When MongoDB\Driver\Manager::__construct() is invoked, a hash is created from its arguments (i.e. URI string and array options). The driver will attempt to find a previously persisted » libmongoc client object for that hash. If an existing client cannot be found for the hash, a new client will be created (and persisted for future use).
Each client contains its own database connections and a view of the server topology (e.g. standalone, replica set, shard cluster). By persisting the client between PHP requests, the driver is able to re-use established database connections and remove the need for » discovering the server topology on each request.

I am not sure, if it's because of this **reusing** old connections, or because of this **adapter** or the driver itself though.

Regards,

Nursultan Turdaliev.

**Comment by alcaeus** [comment]
I'm not exactly sure whether it's related to the driver or the adapter. There's an issue in the MongoDB PHP driver repository (https://github.com/mongodb/mongo-php-driver/issues/501) that might help.

**Comment by nurolopher** [comment]
@alcaeus thanks for a quick response. I appreciate it.

**Comment by jmikola** [comment]
@nurolopher: The adapter doesn't do any connection management, so I'm inclined to think this is purely related to the driver. If you'd like to open a ticket on [mongodb/mongo-php-driver](https://github.com/mongodb/mongo-php-driver), we can look into it further.

I'd also ask whether you've been able to isolate this behavior to a single worker process. That would tell us whether this behavior is all happening within a single libmongoc client object. Any number of networking factors between the MongoDB driver and server(s) could also be responsible for dropped connections, and since a driver does attempt to reconnect after a dropped connection, that would explain why subsequent requests succeed without error. If we aren't isolating this behavior to a single application server, it does make it more difficult to assess the situation, since multiple libmongoc clients will be at play.

If you do open a new issue, I would definitely suggest trying to isolate this to a single PHP worker process and collect some [`mongodb.debug`](http://php.net/manual/en/mongodb.configuration.php) logs for requests over the five minute span. Note that these logs can be quite large, depending on how you utilize the driver, so I definitely have them log to a directory and also avoid collecting this data on a live web server.

**Comment by nurolopher** [comment]
@jmikola thank you. I will open a ticket on [mongodb/mongo-php-driver](https://github.com/mongodb/mongo-php-driver) with everything included listed above.

**Comment by alcaeus** [comment]
@jmikola thank you for your help with this, it is much appreciated!

Closing since it's not an adapter issue.
