### ISSUE TITLE
Unexpected behaviour

### ISSUE THREAD

**Issue by olivier34000** [alcaeus/mongo-php-adapter#165]
With the old driver
```
php -r  'var_dump(http_build_query(["_id" => new \MongoId("58e365dfebde804d4a3c8521")]));'

string(39) "_id%5B%24id%5D=58e365dfebde804d4a3c8521"
```
With the new driver and the library
```
php -r  'require "vendor/autoload.php"; var_dump(http_build_query(["_id" => new \MongoId("58e365dfebde804d4a3c8521")]));'
string(0) ""

php -r  'var_dump(http_build_query(["_id" => new \MongoDB\BSON\ObjectID("58e365dfebde804d4a3c8521")]));'

string(37) "_id%5Boid%5D=58e365dfebde804d4a3c8521"
```
I don't understand what  the function ```http_build_query``` does because the serialization works

**Comment by alcaeus** [comment]
From the [documentation on `http_build_query`](https://secure.php.net/http_build_query):
> If query_data is an object, then only public properties will be incorporated into the result.

Unfortunately, I can't make the `$id` property public since there is some magic involved, namely that it can't be set, which can only be accomplished by having it private and using `__set` to intercept access.

The way `http_build_query` is written makes it impossible to handle this usecase.
