### ISSUE TITLE
dev-master branch is not dealing properly with replicas

### ISSUE THREAD

**Issue by manuelbcd** [alcaeus/mongo-php-adapter#204]
Hi. I would like to report an issue related with MongoDB replicas.

Using the dev-master version of alcaeus adapter we are facing random problems with mongo connection, it seems like if the application is unable to resolve the DB endpoints.
Since it is random I suspect that is related with replaicas and how Atlas is changing master dynamically.

We have changed the composer.json to point to "alcaeus/mongo-php-adapter" : "1.1.3" and the problem seems to be fixed.

**Comment by alcaeus** [comment]
`dev-master` and `1.1.3` both point to the same commit hash (9f42213a51e12c0fc1ce4773840c34d8ab3afd6f), so I suspect there's something else in play. Since this library only proxies calls to the underlying MongoDB library, it'd be interesting to see the version being used there and any errors that are involved.

**Comment by manuelbcd** [comment]
You are right alcaeus it was my fault. The problem seem to be fixed automatically. Probably an eventual issue with the platform.

Thank you
