### ISSUE TITLE
Need MongoDB 5.0 support

### ISSUE THREAD

**Issue by suryadbox** [alcaeus/mongo-php-adapter#291]
I can see following in composer.json
        "mongodb/mongodb": "^1.0.1"
How can we upgrade to higher mongodb extension example: 1.13 (which supports MongoDB 5+) ?

**Comment by alcaeus** [comment]
The constraint allows installing any newer version of the driver, but the library specifically doesn't support any new server features as it retains feature parity with the legacy driver.

**Comment by suryadbox** [comment]
Thanks for the quick update sir. Which is the latest version of Mongo Supported by this library ? 4.2 or 4.4 ?

**Comment by alcaeus** [comment]
The last release of the legacy extension added support for MongoDB 3.0. You might be able to connect to newer server versions, but there are definitely a lot of features in newer versions you won't be able to use. If you need to use a modern MongoDB version, please use the new driver directly instead of relying on this library.
