### ISSUE TITLE
PHP 8.2 compatibility

### ISSUE THREAD

**Issue by dzaharia-godaddy** [alcaeus/mongo-php-adapter#296]
I'm wondering if this lib will get support for PHP 8.2 (released on December 8, 2022`).
The last version of this lib trigger deprecation warnings:

```
Errno: E_DEPRECATED
ErrMsg: Use of "self" in callables is deprecated
File: [...]/vendor/alcaeus/mongo-php-adapter/lib/Alcaeus/MongoDbAdapter/TypeConverter.php
Line: 180
```

Thanks!

**Comment by alcaeus** [comment]
No, it won't: https://github.com/alcaeus/mongo-php-adapter/pull/290#issuecomment-1030329398.

Instead of updating to newer and newer PHP version, it's time to ditch anything that's relying on the legacy driver and use the newer, supported driver (which this is using in the background). I will no longer upgrade this library.
